name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Запускается при пуше тегов вида v1.0.0, v1.2.3 и т.д.
  workflow_dispatch:  # Позволяет запускать вручную
    inputs:
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'

env:
  REGISTRY: docker.io
  IMAGE_NAME: avt548499/avt548499
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Извлекаем версию из тега (убираем 'v')
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        fi
        echo "Using version: $VERSION"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update K8s manifests with new version
      run: |
        # Создаем временный файл с новой версией
        echo "${{ steps.version.outputs.VERSION }}" > image_version.txt
        
        # Обновляем манифесты (если нужно)
        sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}|g" k8s/deployment.yaml

    - name: Upload version file
      uses: actions/upload-artifact@v4
      with:
        name: k8s-manifests
        path: |
          k8s/
          image_version.txt
        retention-days: 1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download version file
      uses: actions/download-artifact@v4
      with:
        name: k8s-manifests

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        # Применяем все манифесты из папки k8s
        kubectl apply -f k8s/ -n ${{ env.K8S_NAMESPACE }}
        
        # Деплой с проверкой
        kubectl rollout status deployment/your-app-deployment -n ${{ env.K8S_NAMESPACE }}
        
        echo "Deployment completed successfully!"